In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random as rd
from math import sqrt

In [2]:
dataTable = pd.read_csv('iris.csv', names =['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'flower'])

In [3]:
xMatrix = np.array(dataTable[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])
yVector = np.array(dataTable['flower'])

In [4]:
dataTable

sepal_length  sepal_width  petal_length  petal_width  flower
0            5.1          3.5           1.4          0.2       0
1            4.9          3.0           1.4          0.2       0
2            4.7          3.2           1.3          0.2       0
3            4.6          3.1           1.5          0.2       0
4            5.0          3.6           1.4          0.2       0
5            5.4          3.9           1.7          0.4       0
6            4.6          3.4           1.4          0.3       0
7            5.0          3.4           1.5          0.2       0
8            4.4          2.9           1.4          0.2       0
9            4.9          3.1           1.5          0.1       0
10           5.4          3.7           1.5          0.2       0
11           4.8          3.4           1.6          0.2       0
12           4.8          3.0           1.4          0.1       0
13           4.3          3.0           1.1          0.1       0
14           5.8          4.0           1.2          0.2       0
15           5.7          4.4           1.5          0.4       0
16           5.4          3.9           1.3          0.4       0
17           5.1          3.5           1.4          0.3       0
18           5.7          3.8           1.7          0.3       0
19           5.1          3.8           1.5          0.3       0
20           5.4          3.4           1.7          0.2       0
21           5.1          3.7           1.5          0.4       0
22           4.6          3.6           1.0          0.2       0
23           5.1          3.3           1.7          0.5       0
24           4.8          3.4           1.9          0.2       0
25           5.0          3.0           1.6          0.2       0
26           5.0          3.4           1.6          0.4       0
27           5.2          3.5           1.5          0.2       0
28           5.2          3.4           1.4          0.2       0
29           4.7          3.2           1.6          0.2       0
..           ...          ...           ...          ...     ...
70           5.9          3.2           4.8          1.8       1
71           6.1          2.8           4.0          1.3       1
72           6.3          2.5           4.9          1.5       1
73           6.1          2.8           4.7          1.2       1
74           6.4          2.9           4.3          1.3       1
75           6.6          3.0           4.4          1.4       1
76           6.8          2.8           4.8          1.4       1
77           6.7          3.0           5.0          1.7       1
78           6.0          2.9           4.5          1.5       1
79           5.7          2.6           3.5          1.0       1
80           5.5          2.4           3.8          1.1       1
81           5.5          2.4           3.7          1.0       1
82           5.8          2.7           3.9          1.2       1
83           6.0          2.7           5.1          1.6       1
84           5.4          3.0           4.5          1.5       1
85           6.0          3.4           4.5          1.6       1
86           6.7          3.1           4.7          1.5       1
87           6.3          2.3           4.4          1.3       1
88           5.6          3.0           4.1          1.3       1
89           5.5          2.5           4.0          1.3       1
90           5.5          2.6           4.4          1.2       1
91           6.1          3.0           4.6          1.4       1
92           5.8          2.6           4.0          1.2       1
93           5.0          2.3           3.3          1.0       1
94           5.6          2.7           4.2          1.3       1
95           5.7          3.0           4.2          1.2       1
96           5.7          2.9           4.2          1.3       1
97           6.2          2.9           4.3          1.3       1
98           5.1          2.5           3.0          1.1       1
99           5.7          2.8          

In [5]:
def crossValidationSplit(xMatrix, yVector, n_folds): 
    xMatrixSplit = []
    yVectorSplit = []
    xMatrixCopy = xMatrix

    yVectorCopy = yVector
    foldSize = int(len(xMatrix) / n_folds) 
    
    for i in range(n_folds): 
        foldXM = [] 
        foldYV = []
        while len(foldXM) < foldSize: 
            index = rd.randrange(len(xMatrixCopy)) 
            foldXM.append(xMatrixCopy[index]) 
            xMatrixCopy = np.delete(xMatrixCopy, index, axis=0)
            foldYV.append(yVectorCopy[index]) 
            yVectorCopy = np.delete(yVectorCopy, index)
        xMatrixSplit.append(foldXM)
        yVectorSplit.append(foldYV)
    return xMatrixSplit, yVectorSplit

def kFoldCrossValidation(xMatrix, yVector, kParts, algorithm, *args):
    xMFolds, yVFolds = crossValidationSplit(xMatrix, yVector, kParts) 
    scores = list() 
    count = 0;
    for fold in xMFolds: 
        xTrain = xMFolds
        yTrain = yVFolds
        
        xTest = xTrain[count]
        yTest = np.array(yTrain[count])
        
        np.delete(xTrain,count)
        np.delete(yTrain,count)
        
        yTrain = np.stack(yTrain)
        yTrain = yTrain.ravel()
        xTrainAux = []

        for i in range(kParts):
            for j in range(len(xTrain[i])):
                xTrainAux.append(xTrain[i][j])
        xTrain = np.stack(xTrainAux)
        yTest = np.where(yTest < 0, 0, yTest)
        predicted = algorithm(xTrain, yTrain, xTest, *args)
        for i in range(len(predicted)):
            print("Predicted: ",predicted[i],"Actual: ",yTest[i])
        accuracy = np.array([x - y for x, y in zip(predicted, yTest)])/kParts
        scores.append(accuracy) 
    return scores

In [6]:
def matriz_covariance(x1, x2):
    return 1

def euclidean_distance(testRow, trainRow):
    distance = 0.0
    for i in range(len(testRow)):
        distance += (testRow[i] - trainRow[i])**2
    return sqrt(distance)

'''
def manhattan_distance(x1, x2):
    return np.sum([abs(i-j) for i, j in zip(x1,x2)])

def mahalanobis_distance_(x1, x2):
    return sqrt(np.transpose([(i-j) for i, j in zip(x1, x2)]) * matriz_covariance(x1,x2) * [(i-j) for i, j in zip(x1,x2)])
'''

def get_neighbors(train, yTrain, testRow, num_neighbors):
    distances = list()
    for i in range(train.shape[0]):
        dist = euclidean_distance(testRow, train[i])
        distances.append((train[i], dist, yTrain[i]))
    distances.sort(key=lambda tup: tup[1])
    neighbors = list()
    for i in range(num_neighbors):
        neighbors.append((distances[i][0], distances[i][2]))
    return neighbors

def predict_classification(train, test, num_neighbors):
    prediction = list()
    for i in range(test.shape[0]):
        neighbors = get_neighbors(train, test.iloc[i], num_neighbors)
        output_values = [row[-1] for row in neighbors]
        prediction.append(max(set(output_values), key=output_values.count))
    return prediction

In [7]:
def knn(xTrain, yTrain, xTest, numNeighbors):
    prediction = list()
    for i in range(len(xTest)):
        neighbors = get_neighbors(xTrain, yTrain, xTest[i], numNeighbors)
        output_values = [row[-1] for row in neighbors]
        prediction.append(max(set(output_values), key=output_values.count))
    return prediction

In [8]:
neighbors = 3
kParts = 5
kFoldCrossValidation(xMatrix, yVector, kParts, knn, neighbors)

Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0


[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.])]