In [14]:
import numpy as np
import pandas as pd

In [15]:
data_table = pd.DataFrame({'Peso': np.array([40.0, 93.5, 35.5, 30.0, 52.0, 17.0, 38.5,  8.5, 33.0,  9.5, 21.0, 79.0]) / 2.205,
                            'Altura': np.array([42.8, 63.5, 37.5, 39.5, 45.5, 38.5, 43.0, 22.5, 37.0, 23.5, 33.0, 58.0]) / 39.37,
                            'Cateter': [37, 50, 34, 36, 43, 28, 37, 20, 34, 30, 38, 47]},
                            dtype='float')

In [16]:
data_table

Peso    Altura  Cateter
0   18.140590  1.087122     37.0
1   42.403628  1.612903     50.0
2   16.099773  0.952502     34.0
3   13.605442  1.003302     36.0
4   23.582766  1.155702     43.0
5    7.709751  0.977902     28.0
6   17.460317  1.092202     37.0
7    3.854875  0.571501     20.0
8   14.965986  0.939802     34.0
9    4.308390  0.596901     30.0
10   9.523810  0.838202     38.0
11  35.827664  1.473203     47.0

In [17]:
data_table.insert(0,"Um", np.ones(len(data_table), dtype = float), True)
xMatrix = data_table[['Um','Peso', 'Altura']].values
yVector = data_table['Cateter'].values
xMatrix

array([[ 1.        , 18.14058957,  1.08712217],
       [ 1.        , 42.40362812,  1.61290323],
       [ 1.        , 16.09977324,  0.95250191],
       [ 1.        , 13.60544218,  1.00330201],
       [ 1.        , 23.58276644,  1.15570231],
       [ 1.        ,  7.70975057,  0.97790196],
       [ 1.        , 17.46031746,  1.09220218],
       [ 1.        ,  3.85487528,  0.57150114],
       [ 1.        , 14.96598639,  0.93980188],
       [ 1.        ,  4.30839002,  0.59690119],
       [ 1.        ,  9.52380952,  0.83820168],
       [ 1.        , 35.8276644 ,  1.47320295]])

In [18]:
yVector

array([37., 50., 34., 36., 43., 28., 37., 20., 34., 30., 38., 47.])

In [20]:
def gradientDescent(xMatrix, yVector, nEpochs, alpha):
    initialW = np.ones(len(xMatrix[0]), dtype = float);
    
    yHat = xMatrix.dot(initialW)    
    
    for i in range(nEpochs):
        summation = 0;
        for y, y_c, x in zip(yVector, yHat, xMatrix):
            summation += (y - y_c) * x
        nextW =  initialW + (alpha/len(xMatrix)) * summation
        yHat = xMatrix.dot(nextW)
        initialW = nextW
    return nextW

In [21]:
gradientDescent(xMatrix, yVector, 1000, 0.001)

array([6.84636062, 1.15378886, 4.53928359])